# Site settings
title: CJ Salonen
description: A Resume For CJ Salonen
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: CJ Salonen
user_description: I'm a Systems Admin from North Dakota, always searching for the next challenge; no task is too scary nor too difficult. My current goal is continued learning of the DevOps world. 
user_title: Systems Admin
email: cj.salonen@gmail.com
# twitter_username: lorem_ipsum
# github_username:  cj-salonen
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']